version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:80"
    networks:
      - fastapi_network

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    container_name: locust
    command: locust -f /locust/locustfile.py --host=http://fastapi:80
    ports:
      - "8089:8089"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
